.PHONY: clean build fmt

fmt:
	go fmt ./...
clean:
	rm -rf ./applyer/applyer ./mpReader/mpReader ./observer/observer

build: clean
	go build -trimpath -o ./applyer/applyer ./applyer/...
	go build -trimpath -o ./mpReader/mpReader ./mpReader/...
	go build -trimpath -o ./observer/observer ./observer/...
